# Generated by Django 6.0.6 on 2026-06-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('region', 'geographyofinterest', 'city', 'town', 'village')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
