# Generated by Django 6.0.6 on 2026-06-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pointofinterest_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text="This character's parents (the reverse side gives their children).", related_name='children', to='api.character'),
        ),
    ]
