# Generated by Django 6.0.6 on 2026-06-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_character_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spouses',
            field=models.ManyToManyField(blank=True, help_text="The character's spouses or partners.", to='api.character'),
        ),
    ]
