# Generated by Django 6.0.6 on 2026-06-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_character_spouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='map_x',
            field=models.FloatField(blank=True, help_text='X position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='map_y',
            field=models.FloatField(blank=True, help_text='Y position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='geographyofinterest',
            name='map_x',
            field=models.FloatField(blank=True, help_text='X position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='geographyofinterest',
            name='map_y',
            field=models.FloatField(blank=True, help_text='Y position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='map_x',
            field=models.FloatField(blank=True, help_text='X position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='map_y',
            field=models.FloatField(blank=True, help_text='Y position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='map_image',
            field=models.ImageField(blank=True, height_field='map_image_height', help_text='A map image for this region (uploaded via the admin).', null=True, upload_to='region_maps/', width_field='map_image_width'),
        ),
        migrations.AddField(
            model_name='region',
            name='map_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='map_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='map_x',
            field=models.FloatField(blank=True, help_text='X position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='map_y',
            field=models.FloatField(blank=True, help_text='Y position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='map_x',
            field=models.FloatField(blank=True, help_text='X position on the parent map, 0-1.', null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='map_y',
            field=models.FloatField(blank=True, help_text='Y position on the parent map, 0-1.', null=True),
        ),
    ]
