# Generated by Django 6.0.6 on 2026-06-27 05:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_city_map_x_city_map_y_geographyofinterest_map_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='map_image',
            field=models.ImageField(blank=True, height_field='map_image_height', help_text='A map image for this place (uploaded via the admin).', null=True, upload_to=api.models.map_image_upload_to, width_field='map_image_width'),
        ),
        migrations.AddField(
            model_name='city',
            name='map_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='map_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='geographyofinterest',
            name='map_image',
            field=models.ImageField(blank=True, height_field='map_image_height', help_text='A map image for this place (uploaded via the admin).', null=True, upload_to=api.models.map_image_upload_to, width_field='map_image_width'),
        ),
        migrations.AddField(
            model_name='geographyofinterest',
            name='map_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='geographyofinterest',
            name='map_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='map_image',
            field=models.ImageField(blank=True, height_field='map_image_height', help_text='A map image for this place (uploaded via the admin).', null=True, upload_to=api.models.map_image_upload_to, width_field='map_image_width'),
        ),
        migrations.AddField(
            model_name='town',
            name='map_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='map_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='map_image',
            field=models.ImageField(blank=True, height_field='map_image_height', help_text='A map image for this place (uploaded via the admin).', null=True, upload_to=api.models.map_image_upload_to, width_field='map_image_width'),
        ),
        migrations.AddField(
            model_name='village',
            name='map_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='map_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='map_image',
            field=models.ImageField(blank=True, height_field='map_image_height', help_text='A map image for this place (uploaded via the admin).', null=True, upload_to=api.models.map_image_upload_to, width_field='map_image_width'),
        ),
    ]
